import { Montserrat } from "next/font/google";
import "./globals.css";
import { StarterApp } from "./StarterApp";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <main className="relative max-w-[400px] max-h-[680px] mx-auto">
          <StarterApp>{children}</StarterApp>
        </main>
      </body>
    </html>
  );
}
